# Use a Python base image
FROM python:3.11-slim

# Configure environment variables
ENV PYTHONUNBUFFERED=1 \
  PYTHONDONTWRITEBYTECODE=1 \
  POETRY_VERSION=1.7.1 \
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_CREATE=false

RUN pip install --upgrade pip && \
  pip install "poetry" 
# Set the working directory

RUN apt-get update && apt-get install -y build-essential python3-dev

COPY pyproject.toml poetry.lock README.md ./

RUN poetry install --no-root

COPY . /app/

WORKDIR /app/

# Expose the port
EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]